### ISSUE TITLE
Log file as txt created by serilog are very weird

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/QualificationRunner#90]
@abdelr @georgeDaskalakis 

I am trying to run the qualificationRunner which starts the PKSim.CLI with some options. 
For instance it looks like so

```
 var args = new List<string>
         {
            "qualification",
            "-i",
            configFile.InQuotes(),
            "-l",
            logFile.InQuotes(),
            "--logLevel",
            logLevel.ToString(),
            "-r"
         };

```

I am passing a logfile path as well as a loglevel. I started the runner as loglevel debug passing the following path for log file
 var logFile = Path.Combine(qualifcationConfiguration.TempFolder, "log.txt");

Here is what is created instead

![image](https://user-images.githubusercontent.com/1041237/133827866-5680f16f-b487-4ba7-9ef8-c263a1dc87d7.png)

- The path given as parameter is ignored (as you can see, the name is log-date.txt??? `log-20210917.txt`
- The logLevel is not Debug but Info (by looking at the output) in the file

```
2021-09-17T13:03:54.4936840-04:00  [INF] Starting validation run... (5fad33c5)
2021-09-17T13:04:02.8727560-04:00  [INF] Starting qualification run... (80cc7546)
```

- Each entry as this weird SHA at the end? 

It is crucial that this is fixed. Specifically, the log file path cannot be ignroed as we are watching for changes in this files.

**Comment by msevestre** [comment]
FYI @Yuri05

**Comment by georgeDaskalakis** [comment]
Currently the SHA and log file name issues are fixed. logLevel is covered in the last open issues, so I suggest we just close this one. 
Just as a note:  the formating of the entries is being set in Core, in OSPSuite.Infrastructure\Services\LoggingBuilderExtensions.cs , line 39, it is the parameter outputTemplate. If there are specific requirements concerning the formatting of the entries, let's put them down on a separate issue and I will implement them. Of course, if it needed to pass this outputTemplate as a parameter so that this template can vary from solution to solution, this would also be easy to implement.
